export const GENERATION = {
     FETCH : 'GENERATION_FETCHH',
     FETCH_ERROR:'GENERATION_FETCH_ERROR',
     FETCH_SUCCESS:'GENERATION_FETCH_SUCCESS'
 };


export const DRAGON = {
    FETCH : 'DRAGON_FETCHH',
    FETCH_ERROR:'DRAGON_FETCH_ERROR',
    FETCH_SUCCESS:'DRAGON_FETCH_SUCCESS'
};

export const ACCOUNT = {
    FETCH : 'ACCOUNT_FETCHH',
    FETCH_ERROR:'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS:'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT_SUCCESS : 'FETCH_LOGOUT_SUCCESS',
    FETCH_LOGIN_SUCCESS : 'FETCH_LOGIN_SUCCESS',
    FETCH_AUTH_SUCCESS:'FETCH_AUTH_SUCCESS'
}; 

export const ACCOUNT_DRAGON = {
    FETCH : 'ACCOUNT_DRAGON_FETCHH',
    FETCH_ERROR:'ACCOUNT_DRAGON_FETCH_ERROR',
    FETCH_SUCCESS:'ACCOUNT_DRAGON_FETCH_SUCCESS'
};

export const ACCOUNT_INFO = {
    FETCH : 'ACCOUNT_INFO_FETCHH',
    FETCH_ERROR:'ACCOUNT_INFO_FETCH_ERROR',
    FETCH_SUCCESS:'ACCOUNT_INFO_FETCH_SUCCESS'
};

export const PUBLIC_DRAGONS = {
    FETCH : 'PUBLIC_DRAGONS_FETCHH',
    FETCH_ERROR:'PUBLIC_DRAGONS_FETCH_ERROR',
    FETCH_SUCCESS:'PUBLIC_DRAGONS_FETCH_SUCCESS'
};